### ISSUE TITLE
是否支持定位监听方法

### ISSUE THREAD

**Issue by DreamPWJ** [yanxiaojun617/com.kit.cordova.amaplocation#3]
定位监听方法时刻获取用户位置信息 是否支持？

**Comment by xiaosan666** [comment]
不支持,可以参考高德android api修改源代码.https://github.com/yanxiaojun617/com.kit.cordova.amaplocation/blob/master/src/android/LocationPlugin.java

**Comment by DreamPWJ** [comment]
感谢  能否直接给添加上  这个功能很常用
